services:
  nextjs-dev:
    build: .
    container_name: nextjs-dev
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    command: npm run dev
